#这个是必须要加的
language: node_js

# 这个也是标配
sudo: required

services:
  - docker

# Running a container checking if it can build the container successfully
before_install:
  #  build client
  - docker build -t alex/client_react -f ./client_react/Dockerfile.dev ./client_react

# Running the test, and expect the test can exit successfully
script:
  - docker run -e CI=true alex/client_react npm test -- --coverage

after_success:
  - docker build -t alex/multi-client ./client_react
  - docker build -t alex/multi-nginx ./nginx
  - docker build -t alex/multi-server ./server
  - docker build -t laex/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push batmandocode/multi-client
  - docker push batmandocode/multi-nginx
  - docker push batmandocode/multi-server
  - docker push batmandocode/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: us-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-west-1-306476627547
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
