version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres_password"
    # error: not initialized
  redis:
    image: "redis:latest"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80" # 这个点很关键，就是把3050 直接 直接暴露给外的
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
      # 进到 /server 中 找 Dockerfile.dev 这个文件
    volumes:
      - /app/node_modules # ignore 这个 node_modules
      - ./server:/app # 这两个文件夹相互 mapping
    environment:
      - REDIS_HOST=redis #这个直接就是 service 的名字
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
